name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and Publish Docker Image
    runs-on: ubuntu-20.04

    steps:
    # Étape 1 : Récupérer le code source
    - name: Checkout code
      uses: actions/checkout@v4

    # Étape 2 : Connexion au registre GitHub Container Registry
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # Étape 3 : Construire l'image Docker
    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest .

    # Étape 4 : Publier l'image Docker dans GitHub Container Registry
    - name: Push Docker image to GitHub Packages
      run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
