name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupération du code
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Connexion à GitHub Packages Registry
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Étape 3 : Construction de l'image Docker
    - name: Build Docker Image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner,, }}/ue19-lab-05:latest .

    # Étape 4 : Publication de l'image Docker
    - name: Push Docker Image
      run: |
        docker push ghcr.io/${{ github.repository_owner,, }}/ue19-lab-05:latest
